### ISSUE TITLE
Empty APA.events output files with test data

### ISSUE THREAD

**Issue by khandarius** [ElkonLab/scAPA#2]
Hi and thanks for the very interesting pipeline! I have a question about the scAPA output files.

I've run scAPA.shell.script with the provided downsampled BAM files of Lukassen et al.. The -sc option was false, otherwise the default settings were used. The run finished without errors and produced the expected output files.

The contents of the file summary.Introns.txt are:
> Number of peaks passed fillter:	 10512 
> Number of significant (FDR < 5%) APA events: 1645 

The contents of the file summary.UTR.txt are:
> Number of peaks passed fillter:	 5847 
> Number of significant (FDR < 5%) APA events: 286 

However, the file APA.events.txt is empty, and the file Intronic.APA.events.txt contains the text:
> x
> p-value
> q-value

Shouldn't the events files contain descriptions of the identified, significant APA events?

-Darius

**Comment by ghost** [comment]
Thanks, Darius,
I'm looking into it.
There is a holiday here so if I don't manage to fix it Today, I'll get back to you middle or end of next week.
Eldad

**Comment by ghost** [comment]
Hi,
The bug has been fixed. 
Thank you for bringing it to our attention.
Eldad
